apiVersion: v1
kind: Secret
metadata:
  name: shopnow-secret
  namespace: shopnow
type: Opaque
stringData:
  MONGODB_URI: mongodb+srv://durganaresh:xxxxxxxxx@cluster.region.mongodb.net/shopnow
  JWT_SECRET: shopnow-secret